//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramDefinitions.Telegrams {
    
    
    /// <summary>
    /// 
    /// </summary>
    public class TelegramIdentifiers {
        
        /// <summary>
        /// Represents telegram TELEGRAM_A identifier.
        /// </summary>
        public const string TELEGRAM_A = "25";
        
        /// <summary>
        /// Represents telegram TELEGRAM_B identifier.
        /// </summary>
        public const string TELEGRAM_B = "44";
    }
}
