//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProconTel.shortbasic {
    
    
    /// <summary>
    /// 
    /// </summary>
    [System.Serializable()]
    public partial class HeaderType {
        
        private System.Int32? _telegramId;
        
        private System.Int32? _telegramLength;
        
        /// <summary>
        /// Initializes a new instance of the <see cref="HeaderType"/> class.
        /// </summary>
        public HeaderType() : 
                this(true) {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="HeaderType"/> class.
        /// </summary>
        /// <param name="initWithDefaultValues">Determines whether the telegram should be initialized with default values.</param>
        public HeaderType(bool initWithDefaultValues) {
            if (initWithDefaultValues) {
                TelegramId = 0;
                TelegramLength = 0;
            }
        }
        
        /// <summary>
        /// Gets or sets the header plus data.
        /// </summary>
        /// <value>The TelegramId.</value>
        [System.Xml.Serialization.XmlElement("TelegramId", IsNullable=true)]
        public System.Int32? TelegramId {
            get {
                return this._telegramId;
            }
            set {
                this._telegramId = value;
            }
        }
        
        /// <summary>
        /// Gets or sets the Message Id.
        /// </summary>
        /// <value>The TelegramLength.</value>
        [System.Xml.Serialization.XmlElement("TelegramLength", IsNullable=true)]
        public System.Int32? TelegramLength {
            get {
                return this._telegramLength;
            }
            set {
                this._telegramLength = value;
            }
        }
    }
}
