//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProconTel.shortbasic {
    
    
    /// <summary>
    /// 
    /// </summary>
    public class TelegramIdentifiers {
        
        /// <summary>
        /// Represents telegram SHORTTELEGRAM identifier.
        /// </summary>
        public const string SHORTTELEGRAM = "111";
        
        /// <summary>
        /// Represents telegram SIMPLETELEGRAM identifier.
        /// </summary>
        public const string SIMPLETELEGRAM = "113";
        
        /// <summary>
        /// Represents telegram TELEGRAM1 identifier.
        /// </summary>
        public const string TELEGRAM1 = "112";
    }
}
