name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./samples
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore -s https://nexus.macrix.eu/repository/nuget/ -s https://api.nuget.org/v3/index.json --force --no-cache
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - uses: actions/upload-artifact@v1
      with:
        name: SimpleEndpoints
        path: ${{ env.working-directory }}/SimpleEndpoints/bin/Release/netstandard2.0
      with:
        name: VisualEndpoints.Wpf
        path: ${{ env.working-directory }}/VisualEndpoints.Wpf/bin/Release/net472
      name: Upload Artifact
